config/routes.rb
Project::Application.routes.draw do

  resources :roles

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "admin/index"
  resources :users
  
  resources :sessions
  

  resources :researches

  resources :student_projects

  resources :clubs

  resources :academics

  resources :staffs

  resources :studies

  resources :employments

  resources :courses

  resources :events
  
  

  root 'welcome#index'
  

end

app/models/academic.rb
class Academic < ActiveRecord::Base



	validates :name, presence: true
	validates :name, length: {minimum: 1}
	validates :name, length: {maximum: 256}
	
	validates :description, presence: true
	validates :description, length: {minimum: 1}
	validates :description, length: {minimum: 500}
	
	
	
end

app/models/club.rb
class Club < ActiveRecord::Base

validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/course.rb
class Course < ActiveRecord::Base

  validates :number, presence: true
  validates :number, length: {minimum: 1}
  validates :number, length: {maximum: 1000}

  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 1000}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  validates :position, presence: true
  validates :position, length: {minimum:1}
  validates :position, length: {maximum:1000}
 
  validates :company, presence: true
  validates :company, length: {minimum:1}
  validates :company, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}


end

app/models/event.rb
class Event < ActiveRecord::Base

  def start_time
    date
  end

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/research.rb
class Research < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}

  validates :url, presence: true
  validates :url, length: {minimum:1}
  validates :url, length: {maximum:1000}
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/staff.rb
class Staff < ActiveRecord::Base


  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 256}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/student_project.rb
class StudentProject < ActiveRecord::Base
  validates :student, presence: true
  validates :student, length: {minimum:1}
  validates :student, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :topic, presence: true
  validates :topic, length: {minimum:1}
  validates :topic, length: {maximum:1000}
  
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/study.rb
class Study < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :roles
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render action: 'show', status: :created, location: @staff }
      else
        format.html { render action: 'new' }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :description, :cis_page, :personal_page, :image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cis_page %><br>
    <%= f.text_field :cis_page %>
  </div>
  <div class="field">
    <%= f.label :personal_page %><br>
    <%= f.text_field :personal_page %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>Listing Staff</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Cis page</th>
      <th>Personal page</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.description %></td>
        <td><%= staff.cis_page %></td>
        <td><%= staff.personal_page %></td>
        <td><%= staff.image %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %><br>
<a href="/admin/index">Back to Options Page</a>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @staff.description %>
</p>

<p>
  <strong>Cis page:</strong>
  <%= @staff.cis_page %>
</p>

<p>
  <strong>Personal page:</strong>
  <%= @staff.personal_page %>
</p>

<p>
  <strong>Image:</strong>
  <%= @staff.image %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>