config/routes.rb
Project::Application.routes.draw do

  resources :roles

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "admin/index"
  resources :users
  
  resources :sessions
  

  resources :researches

  resources :student_projects

  resources :clubs

  resources :academics

  resources :staffs

  resources :studies

  resources :employments

  resources :courses

  resources :events
  
  

  root 'welcome#index'
  

end

app/models/academic.rb
class Academic < ActiveRecord::Base



	validates :name, presence: true
	validates :name, length: {minimum: 1}
	validates :name, length: {maximum: 256}
	
	validates :description, presence: true
	validates :description, length: {minimum: 1}
	validates :description, length: {minimum: 500}
	
	
	
end

app/models/club.rb
class Club < ActiveRecord::Base

validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/course.rb
class Course < ActiveRecord::Base

  validates :number, presence: true
  validates :number, length: {minimum: 1}
  validates :number, length: {maximum: 1000}

  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 1000}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  validates :position, presence: true
  validates :position, length: {minimum:1}
  validates :position, length: {maximum:1000}
 
  validates :company, presence: true
  validates :company, length: {minimum:1}
  validates :company, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}


end

app/models/event.rb
class Event < ActiveRecord::Base

  def start_time
    date
  end

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/research.rb
class Research < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}

  validates :url, presence: true
  validates :url, length: {minimum:1}
  validates :url, length: {maximum:1000}
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/staff.rb
class Staff < ActiveRecord::Base


  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 256}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/student_project.rb
class StudentProject < ActiveRecord::Base
  validates :student, presence: true
  validates :student, length: {minimum:1}
  validates :student, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :topic, presence: true
  validates :topic, length: {minimum:1}
  validates :topic, length: {maximum:1000}
  
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/study.rb
class Study < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :roles
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: [:show, :edit, :update, :destroy]

  # GET /employments
  # GET /employments.json
  def index
    @employments = Employment.all
  end

  # GET /employments/1
  # GET /employments/1.json
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments
  # POST /employments.json
  def create
    @employment = Employment.new(employment_params)

    respond_to do |format|
      if @employment.save
        format.html { redirect_to @employment, notice: 'Employment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employment }
      else
        format.html { render action: 'new' }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employments/1
  # PATCH/PUT /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to @employment, notice: 'Employment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1
  # DELETE /employments/1.json
  def destroy
    @employment.destroy
    respond_to do |format|
      format.html { redirect_to employments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employment_params
      params.require(:employment).permit(:position, :company, :description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employments/_form.html.erb
<%= form_for(@employment) do |f| %>
  <% if @employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
      <% @employment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_area :position %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_area :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<h1>Editing employment</h1>

<%= render 'form' %>

<%= link_to 'Show', @employment %> |
<%= link_to 'Back', employments_path %>

app/views/employments/index.html.erb
<h1>Listing Employment</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employments.each do |employment| %>
      <tr>
        <td><%= employment.position %></td>
        <td><%= employment.company %></td>
        <td><%= employment.description %></td>
        <td><%= link_to 'Show', employment %></td>
        <td><%= link_to 'Edit', edit_employment_path(employment) %></td>
        <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment', new_employment_path %> <br>
<a href="/admin/index">Back to Options Page</a>

app/views/employments/new.html.erb
<h1>New employment</h1>

<%= render 'form' %>

<%= link_to 'Back', employments_path %>

app/views/employments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @employment.position %>
</p>

<p>
  <strong>Company:</strong>
  <%= @employment.company %>
</p>

<p>
  <strong>Description:</strong>
  <%= @employment.description %>
</p>

<%= link_to 'Edit', edit_employment_path(@employment) %> |
<%= link_to 'Back', employments_path %>