config/routes.rb
Project::Application.routes.draw do

  resources :roles

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "admin/index"
  resources :users
  
  resources :sessions
  

  resources :researches

  resources :student_projects

  resources :clubs

  resources :academics

  resources :staffs

  resources :studies

  resources :employments

  resources :courses

  resources :events
  
  

  root 'welcome#index'
  

end

app/models/academic.rb
class Academic < ActiveRecord::Base



	validates :name, presence: true
	validates :name, length: {minimum: 1}
	validates :name, length: {maximum: 256}
	
	validates :description, presence: true
	validates :description, length: {minimum: 1}
	validates :description, length: {minimum: 500}
	
	
	
end

app/models/club.rb
class Club < ActiveRecord::Base

validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/course.rb
class Course < ActiveRecord::Base

  validates :number, presence: true
  validates :number, length: {minimum: 1}
  validates :number, length: {maximum: 1000}

  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 1000}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  validates :position, presence: true
  validates :position, length: {minimum:1}
  validates :position, length: {maximum:1000}
 
  validates :company, presence: true
  validates :company, length: {minimum:1}
  validates :company, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}


end

app/models/event.rb
class Event < ActiveRecord::Base

  def start_time
    date
  end

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/research.rb
class Research < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}

  validates :url, presence: true
  validates :url, length: {minimum:1}
  validates :url, length: {maximum:1000}
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/staff.rb
class Staff < ActiveRecord::Base


  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 256}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/student_project.rb
class StudentProject < ActiveRecord::Base
  validates :student, presence: true
  validates :student, length: {minimum:1}
  validates :student, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :topic, presence: true
  validates :topic, length: {minimum:1}
  validates :topic, length: {maximum:1000}
  
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/study.rb
class Study < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :roles
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index

	@events = Event.all(:order => "date ASC")

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end
  
  def calendar
    @events = Event.all(:order => "date ASC")
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :description, :location)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<%= link_to 'New Event', new_event_path %><br>
<a href="/admin/index">Back to Options Page</a>

  <tbody>
   <%= calendar @events do |event| %>
  <%= link_to event.name, event %>
<% end %>




<br>

app/views/events/new.html.erb
<h1>New event</h1>

<%= form_for :event, url: events_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= datetime_select :event, :date %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </p>
  <p>
    <%= f.submit %>
  </p> <% end %>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>