config/routes.rb
Project::Application.routes.draw do

  resources :roles

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "admin/index"
  resources :users
  
  resources :sessions
  

  resources :researches

  resources :student_projects

  resources :clubs

  resources :academics

  resources :staffs

  resources :studies

  resources :employments

  resources :courses

  resources :events
  
  

  root 'welcome#index'
  

end

app/models/academic.rb
class Academic < ActiveRecord::Base



	validates :name, presence: true
	validates :name, length: {minimum: 1}
	validates :name, length: {maximum: 256}
	
	validates :description, presence: true
	validates :description, length: {minimum: 1}
	validates :description, length: {minimum: 500}
	
	
	
end

app/models/club.rb
class Club < ActiveRecord::Base

validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/course.rb
class Course < ActiveRecord::Base

  validates :number, presence: true
  validates :number, length: {minimum: 1}
  validates :number, length: {maximum: 1000}

  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 1000}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  validates :position, presence: true
  validates :position, length: {minimum:1}
  validates :position, length: {maximum:1000}
 
  validates :company, presence: true
  validates :company, length: {minimum:1}
  validates :company, length: {maximum:1000}

  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}


end

app/models/event.rb
class Event < ActiveRecord::Base

  def start_time
    date
  end

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/research.rb
class Research < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: {minimum:1}
  validates :name, length: {maximum:1000}
 
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}

  validates :url, presence: true
  validates :url, length: {minimum:1}
  validates :url, length: {maximum:1000}
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/staff.rb
class Staff < ActiveRecord::Base


  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :name, length: {maximum: 256}

  validates :description, presence: true
  validates :description, length: {minimum: 1}
  validates :description, length: {maximum: 1000}

end

app/models/student_project.rb
class StudentProject < ActiveRecord::Base
  validates :student, presence: true
  validates :student, length: {minimum:1}
  validates :student, length: {maximum:1000}
 
  validates :time, presence: true
  validates :time, length: {minimum:1}
  validates :time, length: {maximum:1000}

  validates :topic, presence: true
  validates :topic, length: {minimum:1}
  validates :topic, length: {maximum:1000}
  
  validates :description, presence: true
  validates :description, length: {minimum:1}
  validates :description, length: {maximum:1000}
end

app/models/study.rb
class Study < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: { minimum: 1}
  validates :name, length: { maximum: 256}
  
  validates :date, presence: true
  
  validates :description, presence: true
  validates :description, length: { minimum: 1}
  validates :description, length: { maximum: 256 }
  
  validates :location, presence: true
  validates :location, length: { minimum: 1}
  validates :location, length: { maximum: 256}

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :roles
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end


  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render action: 'show', status: :created, location: @study }
      else
        format.html { render action: 'new' }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:name, :date, :location, :description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/studies/_form.html.erb
<%= form_for(@study) do |f| %>
  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<h1>Listing Study Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= study.name %></td>
        <td><%= study.date %></td>
        <td><%= study.location %></td>
        <td><%= study.description %></td>
        <td><%= link_to 'Show', study %></td>
        <td><%= link_to 'Edit', edit_study_path(study) %></td>
        <td><%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study', new_study_path %> <br>
<a href="/admin/index">Back to Options Page</a>

app/views/studies/new.html.erb
<h1>New study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @study.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @study.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @study.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @study.description %>
</p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>